services:
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gorest
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gorest_development
volumes:
  postgres:
